-- Migration: Add new bet type columns to races table
ALTER TABLE races ADD COLUMN IF NOT EXISTS has_plase BOOLEAN DEFAULT FALSE;
ALTER TABLE races ADD COLUMN IF NOT EXISTS has_plase_ikili BOOLEAN DEFAULT FALSE;
ALTER TABLE races ADD COLUMN IF NOT EXISTS has_uclu_bahis BOOLEAN DEFAULT FALSE;
ALTER TABLE races ADD COLUMN IF NOT EXISTS has_7li_ganyan BOOLEAN DEFAULT FALSE;
ALTER TABLE races ADD COLUMN IF NOT EXISTS has_7li_plase BOOLEAN DEFAULT FALSE;
ALTER TABLE races ADD COLUMN IF NOT EXISTS has_3lu_ganyan BOOLEAN DEFAULT FALSE;

