-- Migration: races tablosuna yeni kolon ekle
-- Supabase SQL Editor'da çalıştırın

ALTER TABLE races ADD COLUMN IF NOT EXISTS mesafe INTEGER;
ALTER TABLE races ADD COLUMN IF NOT EXISTS kosul TEXT;
ALTER TABLE races ADD COLUMN IF NOT EXISTS eld TEXT;
ALTER TABLE races ADD COLUMN IF NOT EXISTS ikramiye TEXT;
ALTER TABLE races ADD COLUMN IF NOT EXISTS ekuri TEXT;
ALTER TABLE races ADD COLUMN IF NOT EXISTS has_cifte BOOLEAN DEFAULT FALSE;
ALTER TABLE races ADD COLUMN IF NOT EXISTS has_ikili BOOLEAN DEFAULT FALSE;
ALTER TABLE races ADD COLUMN IF NOT EXISTS has_sirali_ikili BOOLEAN DEFAULT FALSE;

